spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: user
    password: password
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /event/api-docs

server:
  port: 8082