spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations:
        classpath: /src/main/resources/data.sql
      schema-locations:
        classpath: /src/main/resources/schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    ROOT: ERROR
    web: debug