apiVersion: v1
kind: Service
metadata:
  name: hw-docker-service
  namespace: hw17-docker
spec:
  selector:
    app: hw-deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  type: NodePort
  