version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - postgres_db

  event:
    build:
      context: .
      dockerfile: event-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres_db
    depends_on:
      - postgres
    networks:
      - security_event
      - postgres_db

  security:
    build:
      context: .
      dockerfile: security-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - EVENT-SERVICE_BASE-URL=http://event:8082
    depends_on:
      - event
    networks:
      - security_event

volumes:
  postgres_data:

networks:
  postgres_db:
    driver: bridge
  security_event:
    driver: bridge